apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: python-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
        - name: python-webapp
          image: dipshi/app1:274
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/app/data"
              name: my-storage
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: python-webapp-pvc
