apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        - name: python-webapp
          image: dipshi/app1:274
          ports:
            - containerPort: 5000    
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          
