apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: client-a
  name: python-webapp-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
