apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: client-a
  name: python-webapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
