apiVersion: v1
kind: Service
metadata: 
   namespace: client-a
   name: python-webapp
spec:
    selector:
      app: python-webapp
    type: ClusterIP
    ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
